### ISSUE TITLE
thanks!

### ISSUE THREAD

**Issue by dh1tw** [Schwaneberg/pymeterreader#12]
Just wanted to leave a word of appreciation! You project significantly simplifies the setup to monitor the house holds power consumption. SML parsing of our Holley DTZ541-ZEBA works out of the box. The integrated metrics endpoint allows prometheus to directly scrape the data. I really appreciate that I don't have to install and setup the volkszaehler stack.

Thanks!

**Comment by Schwaneberg** [comment]
Thank you very much! I am happy that pymeterreader is satisfying you.
